### ISSUE TITLE
divisions by zero

### ISSUE THREAD

**Issue by matthiaskrgr** [graphitemaster/neothyne#59]
clang-devs -fsanitize=undefined reports a few divisions by zero when running neothyne 
````
[video] => found 1 displays
[video] => searching for display `0'
[video] => found matching display `0' (1600 x 900)
[video] => using display `0'
[video] => Vendor: Intel Open Source Technology Center
[video] => Renderer: Mesa DRI Intel(R) Sandybridge Mobile 
[video] => Driver: 3.0 Mesa 13.0.2
[video] => Shading: 1.30 (using 3.0)
[video] => Extensions:
            GL_ARB_debug_output
            GL_ARB_half_float_vertex
            GL_EXT_texture_compression_rgtc
            GL_EXT_texture_filter_anisotropic
            GL_ARB_texture_rectangle
            GL_ARB_get_program_binary
            GL_EXT_texture_compression_s3tc
[system] => OS: Linux 4.8.12-300.fc25.x86_64 x86_64
[system] => CPU: Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz (4 cores)
[system] => RAM: 11.62 GB
[system] => Game: ./game/
[system] => User: /home/matthias/.local/share/Neothyne/
[audio] => discovered 5 drivers
[audio] => found driver `pulseaudio'
[audio] => 1 playback device present for driver `pulseaudio'
             usable: Built-in Audio Analog Stereo
[audio] => found driver `alsa'
[audio] => 1 playback device present for driver `alsa'
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
             unusable: HDA Intel PCH, CX20590 Analog
[audio] => no usable playback device(s) found for driver `alsa'
[audio] => found driver `dsp'
[audio] => no usable playback device(s) found for driver `dsp'
[audio] => found driver `dummy'
[audio] => 1 playback device present for driver `dummy'
             usable: System audio output device
[audio] => have 3 usable drivers
[audio] => searching for driver `pulseaudio'
[audio] => found matching driver `pulseaudio'
[audio] => using driver `pulseaudio'
[audio] => have 1 usable device
[audio] => searching for device `Built-in Audio Analog Stereo'
[audio] => discovered 1 playback device
[audio] => found matching device `Built-in Audio Analog Stereo'
[audio] => device `Built-in Audio Analog Stereo' configured for 2 channels @ 44100Hz (1024 float samples)
[audio] => initialized for 32 voices @ 44100Hz with 2.00 kB buffer
[script] => inlined operations (assignments: 10, accesses: 31, constraints: 3)
[script] => redirected 2 predictable lookup misses
[script] => generated 2 fast slots (reads: 3, writes: 2)
[script] => inlined operations (assignments: 19, accesses: 53, constraints: 7)
[script] => redirected 0 predictable lookup misses
[script] => generated 1 fast slots (reads: 0, writes: 0)
[script] => inlined operations (assignments: 7, accesses: 65, constraints: 5)
[script] => redirected 37 predictable lookup misses
[script] => generated 6 fast slots (reads: 24, writes: 1)
[script] => inlined operations (assignments: 5, accesses: 34, constraints: 5)
[script] => redirected 4 predictable lookup misses
[script] => generated 5 fast slots (reads: 12, writes: 0)
[script] => inlined operations (assignments: 1, accesses: 6, constraints: 1)
[script] => redirected 4 predictable lookup misses
[script] => generated 1 fast slots (reads: 1, writes: 0)
[script] => inlined operations (assignments: 1, accesses: 6, constraints: 1)
[script] => redirected 4 predictable lookup misses
[script] => generated 1 fast slots (reads: 1, writes: 0)
[script] => inlined operations (assignments: 1, accesses: 6, constraints: 1)
[script] => redirected 4 predictable lookup misses
[script] => generated 1 fast slots (reads: 1, writes: 0)
[script] => inlined operations (assignments: 31, accesses: 98, constraints: 12)
[script] => redirected 0 predictable lookup misses
[script] => generated 0 fast slots (reads: 0, writes: 0)
[script] => inlined operations (assignments: 2, accesses: 18, constraints: 2)
[script] => redirected 3 predictable lookup misses
[script] => generated 2 fast slots (reads: 7, writes: 0)
[script] => inlined operations (assignments: 26, accesses: 58, constraints: 7)
[script] => redirected 1 predictable lookup misses
[script] => generated 1 fast slots (reads: 0, writes: 1)
[script] => inlined operations (assignments: 3, accesses: 11, constraints: 0)
[script] => redirected 3 predictable lookup misses
[script] => generated 1 fast slots (reads: 2, writes: 0)
[script] => inlined operations (assignments: 3, accesses: 11, constraints: 0)
[script] => redirected 3 predictable lookup misses
[script] => generated 1 fast slots (reads: 2, writes: 0)
[script] => inlined operations (assignments: 3, accesses: 9, constraints: 0)
[script] => redirected 3 predictable lookup misses
[script] => generated 1 fast slots (reads: 2, writes: 0)
[script] => inlined operations (assignments: 3, accesses: 11, constraints: 0)
[script] => redirected 3 predictable lookup misses
[script] => generated 1 fast slots (reads: 2, writes: 0)
[script] => inlined operations (assignments: 1, accesses: 11, constraints: 0)
[script] => redirected 2 predictable lookup misses
[script] => generated 1 fast slots (reads: 2, writes: 0)
[script] => inlined operations (assignments: 0, accesses: 3, constraints: 0)
[script] => redirected 2 predictable lookup misses
[script] => generated 0 fast slots (reads: 0, writes: 0)
[script] => inlined operations (assignments: 0, accesses: 4, constraints: 0)
[script] => redirected 2 predictable lookup misses
[script] => generated 0 fast slots (reads: 0, writes: 0)
[script] => inlined operations (assignments: 11, accesses: 1, constraints: 0)
[script] => redirected 0 predictable lookup misses
[script] => generated 1 fast slots (reads: 1, writes: 1)
0.000000, 0.000000
0.200000, 0.400000
0.400000, 0.800000
               * 
              * * 
             *   * 
            * * * * 
           *       * 
          * *     * * 
         *   *   *   * 
        * * * * * * * * 
       *               * 
      * *             * * 
     *   *           *   * 
    * * * *         * * * * 
   *       *       *       * 
  * *     * *     * *     * * 
 *   *   *   *   *   *   *   * 
* * * * * * * * * * * * * * * * 
                               * 
                              * * 
                             *   * 
                            * * * * 
                           *       * 
                          * *     * * 
                         *   *   *   * 
                        * * * * * * * * 
                       *               * 
                      * *             * * 
                     *   *           *   * 
                    * * * *         * * * * 
                   *       *       *       * 
                  * *     * *     * *     * * 
                 *   *   *   *   *   *   *   * 
                * * * * * * * * * * * * * * * * 
               *                               * 
              * *                             * * 
             *   *                           *   * 
            * * * *                         * * * * 
           *       *                       *       * 
          * *     * *                     * *     * * 
         *   *   *   *                   *   *   *   * 
        * * * * * * * *                 * * * * * * * * 
       *               *               *               * 
      * *             * *             * *             * * 
     *   *           *   *           *   *           *   * 
    * * * *         * * * *         * * * *         * * * * 
   *       *       *       *       *       *       *       * 
  * *     * *     * *     * *     * *     * *     * *     * * 
 *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
                                                               * 
                                                              * * 
                                                             *   * 
                                                            * * * * 
                                                           *       * 
                                                          * *     * * 
                                                         *   *   *   * 
                                                        * * * * * * * * 
                                                       *               * 
                                                      * *             * * 
                                                     *   *           *   * 
                                                    * * * *         * * * * 
                                                   *       *       *       * 
                                                  * *     * *     * *     * * 
                                                 *   *   *   *   *   *   *   * 
                                                * * * * * * * * * * * * * * * * 
                                               *                               * 
                                              * *                             * * 
                                             *   *                           *   * 
                                            * * * *                         * * * * 
                                           *       *                       *       * 
                                          * *     * *                     * *     * * 
                                         *   *   *   *                   *   *   *   * 
                                        * * * * * * * *                 * * * * * * * * 
                                       *               *               *               * 
                                      * *             * *             * *             * * 
                                     *   *           *   *           *   *           *   * 
                                    * * * *         * * * *         * * * *         * * * * 
                                   *       *       *       *       *       *       *       * 
                                  * *     * *     * *     * *     * *     * *     * *     * * 
                                 *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 
                                * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
                               *                                                               * 
                              * *                                                             * * 
                             *   *                                                           *   * 
                            * * * *                                                         * * * * 
                           *       *                                                       *       * 
                          * *     * *                                                     * *     * * 
                         *   *   *   *                                                   *   *   *   * 
                        * * * * * * * *                                                 * * * * * * * * 
                       *               *                                               *               * 
                      * *             * *                                             * *             * * 
                     *   *           *   *                                           *   *           *   * 
                    * * * *         * * * *                                         * * * *         * * * * 
                   *       *       *       *                                       *       *       *       * 
                  * *     * *     * *     * *                                     * *     * *     * *     * * 
                 *   *   *   *   *   *   *   *                                   *   *   *   *   *   *   *   * 
                * * * * * * * * * * * * * * * *                                 * * * * * * * * * * * * * * * * 
               *                               *                               *                               * 
              * *                             * *                             * *                             * * 
             *   *                           *   *                           *   *                           *   * 
            * * * *                         * * * *                         * * * *                         * * * * 
           *       *                       *       *                       *       *                       *       * 
          * *     * *                     * *     * *                     * *     * *                     * *     * * 
         *   *   *   *                   *   *   *   *                   *   *   *   *                   *   *   *   * 
        * * * * * * * *                 * * * * * * * *                 * * * * * * * *                 * * * * * * * * 
       *               *               *               *               *               *               *               * 
      * *             * *             * *             * *             * *             * *             * *             * * 
     *   *           *   *           *   *           *   *           *   *           *   *           *   *           *   * 
    * * * *         * * * *         * * * *         * * * *         * * * *         * * * *         * * * *         * * * * 
   *       *       *       *       *       *       *       *       *       *       *       *       *       *       *       * 
  * *     * *     * *     * *     * *     * *     * *     * *     * *     * *     * *     * *     * *     * *     * *     * * 
 *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
Maximum between 2^1 and 2^2 was 0.666667
Maximum between 2^2 and 2^3 was 0.666667
Maximum between 2^3 and 2^4 was 0.636364
Maximum between 2^4 and 2^5 was 0.608696
Maximum between 2^5 and 2^6 was 0.590909
Maximum between 2^6 and 2^7 was 0.576087
Maximum between 2^7 and 2^8 was 0.567416
Maximum between 2^8 and 2^9 was 0.559459
Maximum between 2^9 and 2^10 was 0.554937
Maximum between 2^10 and 2^11 was 0.550101
Maximum between 2^11 and 2^12 was 0.547463
Maximum between 2^12 and 2^13 was 0.544145
Maximum between 2^13 and 2^14 was 0.542443
Maximum between 2^14 and 2^15 was 0.540071
Maximum between 2^15 and 2^16 was 0.538784
Maximum between 2^16 and 2^17 was 0.537044
Maximum between 2^17 and 2^18 was 0.536020
Maximum between 2^18 and 2^19 was 0.534645
Maximum between 2^19 and 2^20 was 0.533779
s_runtime.cpp:371:12: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:62:62: note: nonnull attribute specified here
    #0 0x597ac2 in s::arrayResize(s::State*, s::Object*, s::Object*, s::Object**, unsigned long) /home/matthias/vcs/github/neothyne/s_runtime.cpp:371:5
    #1 0x5a0328 in s::VM::callCallable(s::State*, s::Object*, s::Object*, s::Object**, unsigned long) /home/matthias/vcs/github/neothyne/s_vm.cpp
    #2 0x5ab7ee in s::instrCall(s::VMState*) /home/matthias/vcs/github/neothyne/s_vm.cpp:567:10
    #3 0x59f732 in s::VM::step(s::State*) /home/matthias/vcs/github/neothyne/s_vm.cpp:735:14
    #4 0x59fd68 in s::VM::run(s::State*) /home/matthias/vcs/github/neothyne/s_vm.cpp:764:9
    #5 0x468768 in exec(u::string const&) /home/matthias/vcs/github/neothyne/engine.cpp:1067:9
    #6 0x468768 in entryPoint(int, char**) /home/matthias/vcs/github/neothyne/engine.cpp:1159
    #7 0x468768 in main /home/matthias/vcs/github/neothyne/engine.cpp:1223
    #8 0x7f9bd05a7400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #9 0x4067f9 in _start (/home/matthias/vcs/github/neothyne/neothyne+0x4067f9)

s_runtime.cpp:210:70: runtime error: division by zero
    #0 0x59b8b9 in s::floatMath(s::State*, s::Object*, s::Object*, s::Object**, unsigned long, int) /home/matthias/vcs/github/neothyne/s_runtime.cpp:210:70
    #1 0x5a0328 in s::VM::callCallable(s::State*, s::Object*, s::Object*, s::Object**, unsigned long) /home/matthias/vcs/github/neothyne/s_vm.cpp
    #2 0x5ab7ee in s::instrCall(s::VMState*) /home/matthias/vcs/github/neothyne/s_vm.cpp:567:10
    #3 0x59f718 in s::VM::step(s::State*) /home/matthias/vcs/github/neothyne/s_vm.cpp:734:14
    #4 0x59fd68 in s::VM::run(s::State*) /home/matthias/vcs/github/neothyne/s_vm.cpp:764:9
    #5 0x468768 in exec(u::string const&) /home/matthias/vcs/github/neothyne/engine.cpp:1067:9
    #6 0x468768 in entryPoint(int, char**) /home/matthias/vcs/github/neothyne/engine.cpp:1159
    #7 0x468768 in main /home/matthias/vcs/github/neothyne/engine.cpp:1223
    #8 0x7f9bd05a7400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #9 0x4067f9 in _start (/home/matthias/vcs/github/neothyne/neothyne+0x4067f9)

3.141593
3.141593
3.141591
A(0, 0) = 1
A(0, 1) = 2
A(0, 2) = 3
A(0, 3) = 4
A(0, 4) = 5
A(1, 0) = 2
A(1, 1) = 3
A(1, 2) = 4
A(1, 3) = 5
A(2, 0) = 3
A(2, 1) = 5
A(2, 2) = 7
A(3, 0) = 5
A(3, 1) = 13
A(4, 0) = 13
[atlas] => inserted (512x512) at (0,0) (25.00% usage)
u_misc.h:39:28: runtime error: load of misaligned address 0x7ffcf499ee3a for type 'unsigned int', which requires 4 byte alignment
0x7ffcf499ee3a: note: pointer points here
 00 00  00 00 00 00 00 00 00 00  50 4b 05 06 00 00 00 00  2e 00 2e 00 24 0b 00 00  13 c6 53 00 00 00
              ^ 
    #0 0x55f98c in void u::endianSwap<unsigned int>(unsigned int*, unsigned long) /home/matthias/vcs/github/neothyne/./u_misc.h:39:28
    #1 0x55f98c in u::centralDirectoryHead::endianSwap() /home/matthias/vcs/github/neothyne/u_zip.cpp:80
    #2 0x55b427 in u::zip::open(u::string const&) /home/matthias/vcs/github/neothyne/u_zip.cpp:197:14
    #3 0x6121f1 in r::mountCache() /home/matthias/vcs/github/neothyne/r_texture.cpp:444:28
    #4 0x6121f1 in r::texture2D::load(u::string const&, bool, bool, bool) /home/matthias/vcs/github/neothyne/r_texture.cpp:919
    #5 0x649cbc in r::gui::load(u::string const&) /home/matthias/vcs/github/neothyne/r_gui.cpp:452:19
    #6 0x4468d2 in neoMain(FrameTimer&, a::Audio&, r::World&, int, char**, bool&) /home/matthias/vcs/github/neothyne/game/main.cpp:133:15
    #7 0x468845 in entryPoint(int, char**) /home/matthias/vcs/github/neothyne/engine.cpp:1162:24
    #8 0x468845 in main /home/matthias/vcs/github/neothyne/engine.cpp:1223
    #9 0x7f9bd05a7400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #10 0x4067f9 in _start (/home/matthias/vcs/github/neothyne/neothyne+0x4067f9)

u_misc.h:39:9: runtime error: store to misaligned address 0x7ffcf499ee3a for type 'unsigned int', which requires 4 byte alignment
0x7ffcf499ee3a: note: pointer points here
 00 00  00 00 00 00 00 00 00 00  50 4b 05 06 00 00 00 00  2e 00 2e 00 24 0b 00 00  13 c6 53 00 00 00
              ^ 
    #0 0x55f99c in void u::endianSwap<unsigned int>(unsigned int*, unsigned long) /home/matthias/vcs/github/neothyne/./u_misc.h:39:15
    #1 0x55f99c in u::centralDirectoryHead::endianSwap() /home/matthias/vcs/github/neothyne/u_zip.cpp:80
    #2 0x55b427 in u::zip::open(u::string const&) /home/matthias/vcs/github/neothyne/u_zip.cpp:197:14
    #3 0x6121f1 in r::mountCache() /home/matthias/vcs/github/neothyne/r_texture.cpp:444:28
    #4 0x6121f1 in r::texture2D::load(u::string const&, bool, bool, bool) /home/matthias/vcs/github/neothyne/r_texture.cpp:919
    #5 0x649cbc in r::gui::load(u::string const&) /home/matthias/vcs/github/neothyne/r_gui.cpp:452:19
    #6 0x4468d2 in neoMain(FrameTimer&, a::Audio&, r::World&, int, char**, bool&) /home/matthias/vcs/github/neothyne/game/main.cpp:133:15
    #7 0x468845 in entryPoint(int, char**) /home/matthias/vcs/github/neothyne/engine.cpp:1162:24
    #8 0x468845 in main /home/matthias/vcs/github/neothyne/engine.cpp:1223
    #9 0x7f9bd05a7400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #10 0x4067f9 in _start (/home/matthias/vcs/github/neothyne/neothyne+0x4067f9)

[cache] => mounted texture cache `/home/matthias/.local/share/Neothyne/cache/textures.zip'
[cache] => loaded (texture) ECA39AD59984B151 RED_RGTC1 (170.68 kB)
[cache] => mounted method cache `/home/matthias/.local/share/Neothyne/cache/methods.zip'
[method] => loaded `user interface' program
[method] => loaded `user interface' program using [FONT]
[method] => loaded `user interface' program using [IMAGE]
[method] => loaded `user interface model rendering' program
[method] => loaded `user interface model rendering' program using [SCROLL]
[world] => loaded
m_vec.cpp:65:42: runtime error: division by zero
    #0 0x5c88e3 in m::vec3::rayCylinderIntersect(m::vec3 const&, m::vec3 const&, m::vec3 const&, m::vec3 const&, float, float*) /home/matthias/vcs/github/neothyne/m_vec.cpp:65:42
    #1 0x476224 in kdMap::sphereTriangleIntersect(unsigned long, m::vec3 const&, float, m::vec3 const&, float*, m::vec3*, m::vec3*) const /home/matthias/vcs/github/neothyne/kdmap.cpp:259:14
    #2 0x4778ce in kdMap::traceSphere(kdSphereTrace*, int) /home/matthias/vcs/github/neothyne/kdmap.cpp:320:21
    #3 0x44f5a7 in world::trace(world::trace::query const&, world::trace::hit*, float, bool, world::descriptor*) /home/matthias/vcs/github/neothyne/game/world.cpp:233:11
    #4 0x44154e in client::update(world&, float) /home/matthias/vcs/github/neothyne/game/client.cpp:74:13
    #5 0x446f1e in neoMain(FrameTimer&, a::Audio&, r::World&, int, char**, bool&) /home/matthias/vcs/github/neothyne/game/main.cpp:233:17
    #6 0x468845 in entryPoint(int, char**) /home/matthias/vcs/github/neothyne/engine.cpp:1162:24
    #7 0x468845 in main /home/matthias/vcs/github/neothyne/engine.cpp:1223
    #8 0x7f9bd05a7400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #9 0x4067f9 in _start (/home/matthias/vcs/github/neothyne/neothyne+0x4067f9)

[method] => loaded `geometry' program
[method] => loaded `geometry' program using [DIFFUSE]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP]
[method] => loaded `geometry' program using [DIFFUSE, SPECMAP]
[method] => loaded `geometry' program using [DIFFUSE, SPECPARAMS]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECMAP]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECPARAMS]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, PARALLAX]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECMAP, PARALLAX]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECPARAMS, PARALLAX]
[method] => loaded `geometry' program using [DIFFUSE, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, SPECMAP, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, SPECPARAMS, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECMAP, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECPARAMS, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, PARALLAX, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECMAP, PARALLAX, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECPARAMS, PARALLAX, ANIMATION]
[method] => loaded `geometry' program using [SKELETAL]
[method] => loaded `geometry' program using [DIFFUSE, SKELETAL]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SKELETAL]
[method] => loaded `geometry' program using [DIFFUSE, SPECMAP, SKELETAL]
[method] => loaded `geometry' program using [DIFFUSE, SPECPARAMS, SKELETAL]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SKELETAL]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECMAP, SKELETAL]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECPARAMS, SKELETAL]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, PARALLAX, SKELETAL]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECMAP, PARALLAX, SKELETAL]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECPARAMS, PARALLAX, SKELETAL]
[method] => loaded `geometry' program using [DIFFUSE, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, SKELETAL, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SKELETAL, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, SPECMAP, SKELETAL, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, SPECPARAMS, SKELETAL, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SKELETAL, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECMAP, SKELETAL, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECPARAMS, SKELETAL, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, PARALLAX, SKELETAL, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECMAP, PARALLAX, SKELETAL, ANIMATION]
[method] => loaded `geometry' program using [DIFFUSE, NORMALMAP, SPECPARAMS, PARALLAX, SKELETAL, ANIMATION]
[model] => loaded static model `models/plane' (containing 1 material) using single-precision float
m_trig.cpp:417:22: runtime error: division by zero
    #0 0x5cd947 in m::log2(float) /home/matthias/vcs/github/neothyne/m_trig.cpp:417:22
    #1 0x5e2fcd in r::material::load(u::map<u::string, r::texture2D*>&, u::string const&, u::string const&) /home/matthias/vcs/github/neothyne/r_model.cpp:410:23
    #2 0x5e8744 in r::model::load(u::map<u::string, r::texture2D*>&, u::string const&) /home/matthias/vcs/github/neothyne/r_model.cpp:604:29
    #3 0x64cd33 in r::gui::render(r::pipeline const&) /home/matthias/vcs/github/neothyne/r_gui.cpp:609:26
    #4 0x447254 in neoMain(FrameTimer&, a::Audio&, r::World&, int, char**, bool&) /home/matthias/vcs/github/neothyne/game/main.cpp
    #5 0x468845 in entryPoint(int, char**) /home/matthias/vcs/github/neothyne/engine.cpp:1162:24
    #6 0x468845 in main /home/matthias/vcs/github/neothyne/engine.cpp:1223
    #7 0x7f9bd05a7400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #8 0x4067f9 in _start (/home/matthias/vcs/github/neothyne/neothyne+0x4067f9)

[model] => loaded static model `models/logo' (containing 1 material) using half-precision float
[model] => loaded static model `models/icon' (containing 1 material) using half-precision float
[atlas] => inserted (50x50) at (512,0) (25.24% usage)
[atlas] => inserted (50x50) at (562,0) (25.48% usage)
[atlas] => inserted (50x50) at (612,0) (25.72% usage)
[atlas] => inserted (50x50) at (662,0) (25.95% usage)
[atlas] => inserted (4x50) at (712,0) (25.97% usage)
[atlas] => inserted (4x50) at (716,0) (25.99% usage)
[atlas] => inserted (50x4) at (720,0) (26.01% usage)
[atlas] => inserted (50x4) at (720,4) (26.03% usage)
[atlas] => inserted (2x2) at (720,8) (26.03% usage)
[atlas] => inserted (24x68) at (512,50) (26.19% usage)
[atlas] => inserted (212x68) at (536,50) (27.56% usage)
[atlas] => inserted (24x68) at (512,118) (27.72% usage)
[atlas] => inserted (32x32) at (722,8) (27.81% usage)
[atlas] => inserted (24x68) at (512,186) (27.97% usage)
[atlas] => inserted (212x68) at (748,50) (29.34% usage)
[atlas] => inserted (24x68) at (512,254) (29.50% usage)
[cache] => loaded (texture) D8EE52799B82CE98 RGBA_S3TC_DXT1 (128.00 kB)
[cache] => loaded (texture) F250D199B2542B83 RGBA_S3TC_DXT1 (128.00 kB)
[cache] => loaded (texture) D1E6308F12C6FD60 RGBA_S3TC_DXT1 (128.00 kB)
[cache] => loaded (texture) 659FA566FC64817F RGBA_S3TC_DXT1 (128.00 kB)
[cache] => loaded (texture) AD087A91449C3106 RGBA_S3TC_DXT1 (128.00 kB)
[cache] => loaded (texture) F0BFBD577BA8B2AF RGBA_S3TC_DXT1 (128.00 kB)
[method] => loaded `skybox' program
[method] => loaded `skybox' program using [FOG]
[cache] => loaded (texture) 9E000EF180261B6B RGBA_S3TC_DXT1 (682.68 kB)
[cache] => loaded (texture) F4CBCDC2B134435A RED_GREEN_RGTC2 (1.33 MB)
[model] => loaded static model `models/lg' (containing 1 material) using single-precision float
[cache] => loaded (texture) 2E0522332E052233 RGBA_S3TC_DXT5 (21.36 kB)
[method] => loaded `particle system' program
[cache] => loaded (texture) 9DB28107BFF49732 RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) 1A9D54EFB9E81FD1 RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) 4563CD8396C720FF RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) 9F111F80567B6DEA RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) 0C8EC1BD88488045 RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) FB1CD3443ADDA252 RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) B129F6C688805400 RGBA_S3TC_DXT1 (42.68 kB)
[cache] => loaded (texture) D76E6B706538F301 RGBA_S3TC_DXT1 (42.68 kB)
[cache] => loaded (texture) EF243E4BCCB63B23 RED_GREEN_RGTC2 (85.36 kB)
[cache] => loaded (texture) 61C69EF6250E1345 RED_RGTC1 (42.68 kB)
[cache] => loaded (texture) 421771D49A850B84 RGBA_S3TC_DXT1 (42.68 kB)
[cache] => loaded (texture) 42831D689ABDA374 RGBA_S3TC_DXT1 (42.68 kB)
[cache] => loaded (texture) 6FA72B6742D2991D RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) A12C3AAD7F09611E RED_GREEN_RGTC2 (341.36 kB)
[cache] => loaded (texture) 7EF40700D499FEEC RED_RGTC1 (170.68 kB)
[cache] => loaded (texture) 1BDC9AC58114D261 RGBA_S3TC_DXT1 (16.04 kB)
[cache] => loaded (texture) 67EBA0441F6DD104 RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) 6492F26264AC1353 RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) BC2249953137BAA5 RGBA_S3TC_DXT1 (21.38 kB)
[cache] => loaded (texture) D988887C877AA0A8 RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) 310308B15DAACDEC RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) 24E37A6882B741C1 RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) A5CEB8CC3E64C114 RGBA_S3TC_DXT1 (10.70 kB)
[cache] => loaded (texture) 9015EF2184598BC2 RED_GREEN_RGTC2 (21.39 kB)
[cache] => loaded (texture) 751B9A2E96B22BD2 RED_RGTC1 (10.70 kB)
[cache] => loaded (texture) 188C2F2EF3AF8553 RGBA_S3TC_DXT1 (5.35 kB)
[cache] => loaded (texture) 292AC057D900A486 RGBA_S3TC_DXT1 (42.68 kB)
[cache] => loaded (texture) 983F4A5C22C372FD RED_GREEN_RGTC2 (85.36 kB)
[cache] => loaded (texture) 258C420DE757B328 RED_RGTC1 (42.68 kB)
[cache] => loaded (texture) 9F89440D3E220195 RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) 246E7EBDDE368810 RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) A706930C672A7FE8 RGBA_S3TC_DXT1 (170.68 kB)
[cache] => loaded (texture) 9C47D1079B78E9A1 RGBA_S3TC_DXT1 (170.68 kB)
[method] => loaded `composite' program using [TEXTURE_RECTANGLE]
[method] => loaded `anti-aliasing' program using [TEXTURE_RECTANGLE]
[method] => loaded `directional lighting' program using [TEXTURE_RECTANGLE]
[method] => loaded `directional lighting' program using [TEXTURE_RECTANGLE, SSAO]
[method] => loaded `directional lighting' program using [TEXTURE_RECTANGLE, SSAO, FOG]
[method] => loaded `directional lighting' program using [TEXTURE_RECTANGLE, FOG]
[method] => loaded `directional lighting' program using [TEXTURE_RECTANGLE, DEBUG_DEPTH]
[method] => loaded `directional lighting' program using [TEXTURE_RECTANGLE, DEBUG_NORMAL]
[method] => loaded `directional lighting' program using [TEXTURE_RECTANGLE, DEBUG_POSITION]
[method] => loaded `directional lighting' program using [TEXTURE_RECTANGLE, DEBUG_SSAO]
[method] => loaded `point lighting' program using [TEXTURE_RECTANGLE]
[method] => loaded `point lighting' program using [TEXTURE_RECTANGLE, SHADOWMAP]
[method] => loaded `spot lighting' program using [TEXTURE_RECTANGLE]
[method] => loaded `spot lighting' program using [TEXTURE_RECTANGLE, SHADOWMAP]
[method] => loaded `bounding box' program
[method] => loaded `default' program using [TEXTURE_RECTANGLE]
[method] => loaded `screen space ambient occlusion' program using [TEXTURE_RECTANGLE]
[method] => loaded `vignette' program using [TEXTURE_RECTANGLE]
[method] => loaded `shadow map' program
[world] => uploaded
[cache] => loaded (texture) 54CCAA7C54CCAA7C RGBA_S3TC_DXT5 (85.36 kB)
[method] => loaded `billboarding' program
[cache] => loaded (texture) F7786C9D1341E365 RGBA_S3TC_DXT1 (682.68 kB)
[cache] => loaded (texture) 9FFC3B670C3147A1 RGBA_S3TC_DXT1 (170.68 kB)
[model] => loaded animated model `models/iqmtest' (containing 2 materials) using half-precision float
[model] => loaded static model `models/cube' (containing 1 material) using half-precision float
[model] => loaded static model `models/ball' (containing 2 materials) using half-precision float
[atlas] => inserted (68x24) at (770,0) (29.66% usage)
[atlas] => inserted (68x240) at (536,118) (31.21% usage)
[atlas] => inserted (68x24) at (770,24) (31.37% usage)
[atlas] => inserted (64x24) at (838,0) (31.51% usage)
[atlas] => inserted (64x4) at (838,24) (31.54% usage)
[atlas] => inserted (64x24) at (902,0) (31.69% usage)
[world] => unloaded
````

**Comment by matthiaskrgr** [comment]
This has been fixed via 4a4838bda1420ba6192f4833dd23e3aa837ca8c5
