### ISSUE TITLE
double free

### ISSUE THREAD

**Issue by matthiaskrgr** [graphitemaster/neothyne#64]
launch game
hit e for edit mode
f12 for color menu
exit game 

````
[model] => loaded static model `models/ball' (containing 2 materials) using half-precision float
[atlas] => inserted (24x68) at (512,322) (29.66% usage)
[atlas] => inserted (240x68) at (536,118) (31.21% usage)
[atlas] => inserted (24x68) at (512,390) (31.37% usage)
[atlas] => inserted (24x64) at (960,50) (31.51% usage)
[atlas] => inserted (24x64) at (984,50) (31.66% usage)
[atlas] => inserted (68x68) at (776,118) (32.10% usage)
[atlas] => inserted (220x68) at (536,186) (33.53% usage)
[atlas] => inserted (120x68) at (844,118) (34.31% usage)
[atlas] => inserted (120x68) at (536,254) (35.08% usage)
[world] => unloaded
=================================================================
==18580==ERROR: AddressSanitizer: attempting double-free on 0x603000529060 in thread T0:
    #0 0x7f30b7dc4af0 in free (/lib64/libasan.so.3+0xc6af0)
    #1 0x572820 in neoCoreFree /home/matthias/vcs/github/neothyne/u_new.cpp:33
    #2 0x572ab4 in alignedAllocator<false>::neoFree(void*) /home/matthias/vcs/github/neothyne/u_new.cpp:50
    #3 0x572920 in neoFree(void*) /home/matthias/vcs/github/neothyne/u_new.cpp:127
    #4 0x41b5e9 in u::buffer<char const*>::~buffer() /home/matthias/vcs/github/neothyne/u_buffer.h:166
    #5 0x417070 in u::vector<char const*>::~vector() /home/matthias/vcs/github/neothyne/u_vector.h:207
    #6 0x7f30b694341f in __run_exit_handlers (/lib64/libc.so.6+0x3a41f)
    #7 0x7f30b6943479 in __GI_exit (/lib64/libc.so.6+0x3a479)
    #8 0x7f30b6929407 in __libc_start_main (/lib64/libc.so.6+0x20407)
    #9 0x403869 in _start (/home/matthias/vcs/github/neothyne/neothyne+0x403869)

0x603000529060 is located 0 bytes inside of 32-byte region [0x603000529060,0x603000529080)
freed by thread T0 here:
    #0 0x7f30b7dc4af0 in free (/lib64/libasan.so.3+0xc6af0)
    #1 0x572820 in neoCoreFree /home/matthias/vcs/github/neothyne/u_new.cpp:33
    #2 0x572ab4 in alignedAllocator<false>::neoFree(void*) /home/matthias/vcs/github/neothyne/u_new.cpp:50
    #3 0x572920 in neoFree(void*) /home/matthias/vcs/github/neothyne/u_new.cpp:127
    #4 0x41b5e9 in u::buffer<char const*>::~buffer() /home/matthias/vcs/github/neothyne/u_buffer.h:166
    #5 0x417070 in u::vector<char const*>::~vector() /home/matthias/vcs/github/neothyne/u_vector.h:207
    #6 0x7f30b694341f in __run_exit_handlers (/lib64/libc.so.6+0x3a41f)

previously allocated by thread T0 here:
    #0 0x7f30b7dc5200 in realloc (/lib64/libasan.so.3+0xc7200)
    #1 0x5727af in neoCoreRealloc /home/matthias/vcs/github/neothyne/u_new.cpp:22
    #2 0x572a80 in alignedAllocator<false>::neoRealloc(void*, unsigned long) /home/matthias/vcs/github/neothyne/u_new.cpp:46
    #3 0x57287c in neoRealloc(void*, unsigned long) /home/matthias/vcs/github/neothyne/u_new.cpp:117
    #4 0x42ae84 in u::buffer<char const*>::reserve_traits(char const**, char const**, unsigned long, u::detail::is_pod<char const*, true>) /home/matthias/vcs/github/neothyne/u_buffer.h:81
    #5 0x429868 in u::buffer<char const*>::reserve(char const**, char const**, unsigned long) /home/matthias/vcs/github/neothyne/u_buffer.h:85
    #6 0x425880 in u::buffer<char const*>::reserve(unsigned long) /home/matthias/vcs/github/neothyne/u_buffer.h:207
    #7 0x420b1c in u::buffer<char const*>::insert_common(char const**, unsigned long) /home/matthias/vcs/github/neothyne/u_buffer.h:241
    #8 0x41bea6 in void u::buffer<char const*>::insert<char const*>(char const**, char const* const*, char const* const*) /home/matthias/vcs/github/neothyne/u_buffer.h:270
    #9 0x417447 in u::vector<char const*>::vector(std::initializer_list<char const*>) /home/matthias/vcs/github/neothyne/u_vector.h:201
    #10 0x4110b0 in menuEdit game/menu.cpp:693
    #11 0x4151c1 in menuUpdate() game/menu.cpp:880
    #12 0x438c2b in neoMain(FrameTimer&, a::Audio&, r::World&, int, char**, bool&) game/main.cpp:345
    #13 0x4636ef in entryPoint /home/matthias/vcs/github/neothyne/engine.cpp:1168
    #14 0x463883 in main /home/matthias/vcs/github/neothyne/engine.cpp:1229
    #15 0x7f30b6929400 in __libc_start_main (/lib64/libc.so.6+0x20400)

SUMMARY: AddressSanitizer: double-free (/lib64/libasan.so.3+0xc6af0) in free
==18580==ABORTING
````

**Comment by matthiaskrgr** [comment]
Ok, this was on top of https://github.com/graphitemaster/neothyne/pull/63 , without the game HUAFs before

**Comment by graphitemaster** [comment]
will be fixed as a consequence of game rewrite in neolang soon
